### ISSUE TITLE
How zit fetch works?

### ISSUE THREAD

**Issue by Ryokki** [ReZeroS/git#4]
I'm trying to understand how zit fetch works, but failed. When I run code And execute zit fetch origin, it seems not fetch anything from remote branch. Can you explain it?

**Comment by rezeross** [comment]
> I'm trying to understand how zit fetch works, but failed. When I run code And execute zit fetch origin, it seems not fetch anything from remote branch. Can you explain it?

sorry, it did not implment the real fetch feature, in thr tutorial yoi can check that the fetch command is just download the content of .git directory, you can use ssh or https, but that is not the core point for tutorial,  so I just use another local directory as remote repository, so I can replace the  download process with copy command.

**Comment by Ryokki** [comment]
Thanks for your code and your reply.I now understand what "zit fetch" is doing, and I realize that implementing a real fetch is a tricky task.
